version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
          - POSTGRES_DB=airflow
        ports:
          - 5432:5432
        volumes:
          - ./etl_home/bin/initial/database_user.sql:/docker-entrypoint-initdb.d/database_user.sql
          - ./etl_home/bin/initial/dwh_tables.sql:/docker-entrypoint-initdb.d/dwh_tables.sql
          - ./etl_home/bin/initial/populate_tables.sql:/docker-entrypoint-initdb.d/populate_tables.sql
          #- ./etl_home/etl_base/sql/DEMO-MERGE.ddl:/docker-entrypoint-initdb.d/DEMO-MERGE.ddl
          #- ./etl_home/bin/initial/SQLG-WRAPUP.sql:/docker-entrypoint-initdb.d/SQLG-WRAPUP.sql
    webserver:
        image: puckel/docker-airflow:latest
        restart: always
        depends_on:
          - postgres
        environment:
          - LOAD_EX=n
          - EXECUTOR=Local
          - AIRFLOW__CORE__FERNET_KEY=xfaECYb20a2PzNTcIYXFXztTlaEVD43KwUoXeer_83k=
          - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        volumes:
          - ./etl_home/etl_base/dags:/usr/local/airflow/dags
          - ./etl_home/etl_base/sql:/usr/local/airflow/sql
          - ./etl_home/bin:/usr/local/airflow/bin
          - ./etl_home/logs:/usr/local/airflow/logs
          - ./etl_home/etl_base/requirements.txt:/requirements.txt
        ports:
          - 8080:8080
        command: webserver
        #command: airflow variables -s sql_path "/usr/local/airflow/sql"


