version: '2'
services:
  mssql:
      image: microsoft/mssql-server-linux:latest
      container_name: docker-mssql
      environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=Th1sS3cret!
          - POSTGRES_DB=airflow
      ports:
          - 1433:1433
  postgres:
      image: postgres:9.6
      environment:
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
          - POSTGRES_DB=airflow
      ports:
          - 5432:5432
      volumes:
          - ./examples/do-this-first/database_user.sql:/docker-entrypoint-initdb.d/database_user.sql
          - ./examples/do-this-first/dwh_tables.sql:/docker-entrypoint-initdb.d/dwh_tables.sql
          - ./examples/do-this-first/populate_tables.sql:/docker-entrypoint-initdb.d/populate_tables.sql
  webserver:
      image: test/airflow:1.0
      restart: always
      depends_on:
          - postgres
          - mssql
      environment:
          - LOAD_EX=n
          - EXECUTOR=Local
      volumes:
          - ./examples/mssql-example/dags:/usr/local/airflow/dags
          - ./examples/mssql-example/sql:/usr/local/airflow/sql
      ports:
          - 8080:8080
      command: webserver

