---------------------------------------------------------------------
-- {{DWH}}.SQL script for PG, generated by Macro        
-- Date Time       : 8/10/2018 1:38:54 AM
-- Target Table    : O_PRODUCT
-- Script File     : O_PRODUCT.sql
-- Programmer      : JESSE
-- Function        : From (PRODUCT) tables  into {{DWH}}.O_PRODUCT
-- Remarks         :                                                 
---------------------------------------------------------------------
-----------------     Revision History      -------------------------
--   Seq. No.    DATE         By         REASON 
---- -------- ----------- ----------- -------------------------------
--                                                                   
---------------------------------------------------------------------



TRUNCATE TABLE DWH.O_PRODUCT_TP1;

INSERT INTO DWH.O_PRODUCT_TP1 (
      PRODUCT_ID                              
      ,PRODUCT_NAME                            
      ,SUPPLIER_ID                             
      ,PRODUCTTYPE_ID                          
      ,UPDATED_DTM                             
)
      SELECT
       MA.PRODUCT_ID                      AS PRODUCT_ID
      ,MA.PRODUCT_NAME                    AS PRODUCT_NAME
      ,MA.SUPPLIER_ID                     AS SUPPLIER_ID
      ,MA.PRODUCTTYPE_ID                  AS PRODUCTTYPE_ID
      ,%(window_start_date)s              AS UPDATED_DTM
FROM STAGING.PRODUCT as MA  
;


TRUNCATE TABLE DWH.O_PRODUCT;

INSERT INTO DWH.O_PRODUCT (
      PRODUCT_ID                              
      ,PRODUCT_NAME                            
      ,SUPPLIER_ID                             
      ,PRODUCTTYPE_ID                          
      ,UPDATED_DTM                             
) 
      SELECT
      MA.PRODUCT_ID                           
      ,MA.PRODUCT_NAME                         
      ,MA.SUPPLIER_ID                          
      ,MA.PRODUCTTYPE_ID                       
      ,MA.UPDATED_DTM                          
FROM DWH.O_PRODUCT_TP1 as MA ; 


-- Update statistics
;

