
# -*- coding: utf-8 -*-
# Author        : Jesse Wei
# LastUpdate    : 2018/08/04
# Impact        : DAG generated by SQLG
# Message       : Humanity towards others, we live by sharing. Fear can hold you prisoner, only hope can set you free.

# from __future__ import print_function
import logging
import airflow
from datetime import datetime, timedelta
from airflow.operators.sensors import ExternalTaskSensor
from airflow.operators.python_operator import PythonOperator
from airflow import models
from airflow.models import Variable
import sqlg_jobs 

#from acme.operators.dwh_operators import PostgresOperatorWithTemplatedParams

def f_SYS_STS_STG():
    logging.info('Control flow: STAGE status ')

args = {
    'owner': 'airflow',
    'start_date': airflow.utils.dates.days_ago(7),
    'provide_context': True
}

tmpl_search_path = Variable.get("sql_path")

my_taskid = 'SYS_STS_STG'
D_STG_INIT = airflow.DAG(
    'D_STG_INIT',
    schedule_interval=timedelta(1),
    default_args=args,
    template_searchpath=tmpl_search_path,    
    max_active_runs=1)

SYS_STS_STG = PythonOperator(task_id=my_taskid,
                    python_callable=f_SYS_STS_STG,
                    provide_context=False,
                    dag=D_STG_INIT)

my_taskid = 'D_STG_INITxSYS_STS_STG'                    
D_STG_INITxSYS_STS_STG = ExternalTaskSensor(
    task_id=my_taskid,
    external_dag_id='D_STG_INIT',
    external_task_id='SYS_STS_STG',
    execution_delta=None,  # Same day as today
    )

# Flow dag    
DB_NAME = 'DWH'    
D_DWH_ORD_10 = airflow.DAG(    "D_DWH_ORD_10",
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(7),    
    max_active_runs=1)

sqlg_jobs.O_CUSTOMER.dag=D_DWH_ORD_10
D_STG_INITxSYS_STS_STG.dag=D_DWH_ORD_10
D_STG_INITxSYS_STS_STG.set_downstream(sqlg_jobs.O_CUSTOMER)
sqlg_jobs.O_ORDER_INFO.dag=D_DWH_ORD_10
D_STG_INITxSYS_STS_STG.dag=D_DWH_ORD_10
D_STG_INITxSYS_STS_STG.set_downstream(sqlg_jobs.O_ORDER_INFO)
sqlg_jobs.O_ORDERLINE.dag=D_DWH_ORD_10
D_STG_INITxSYS_STS_STG.dag=D_DWH_ORD_10
D_STG_INITxSYS_STS_STG.set_downstream(sqlg_jobs.O_ORDERLINE)
sqlg_jobs.O_PRODUCT.dag=D_DWH_ORD_10
D_STG_INITxSYS_STS_STG.dag=D_DWH_ORD_10
D_STG_INITxSYS_STS_STG.set_downstream(sqlg_jobs.O_PRODUCT)

